server:
  port: ${secrets.DEV_SERVER_PORT}

spring:
  application:
    name: instagram

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${secrets.DEV_RDS_HOST}
    username: ${secrets.DEV_RDS_USERNAME}
    password: ${secrets.DEV_RDS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${secrets.DEV_DDL_AUTO}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace