server:
  port: ${secrets.DEV_SERVER_PORT}

spring:
  application:
    name: instagram

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${secrets.DEV_RDS_HOST}
    username: ${secrets.DEV_RDS_USERNAME}
    password: ${secrets.DEV_RDS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${secrets.DEV_DDL_AUTO}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true

  redis:
    host: ${secrets.DEV_REDIS_HOST}
    port: ${secrets.DEV_REDIS_PORT}


jwt:
  secret-key: ${secrets.DEV_JWT_SECRET_KEY}
  access-token-expire-time: ${secrets.DEV_JWT_ACCESS_TOKEN_EXPIRE_TIME}
  refresh-token-expire-time: ${secrets.DEV_JWT_REFRESH_TOKEN_EXPIRE_TIME}
  refresh-token-reissue-time: ${secrets.DEV_JWT_REFRESH_TOKEN_REISSUE_TIME}
  access-token-header-name: ${secrets.DEV_JWT_ACCESS_TOKEN_HEADER_NAME}
  refresh-token-header-name: ${secrets.DEV_JWT_REFRESH_TOKEN_HEADER_NAME}
  member-id-header-name: ${secrets.DEV_MEMBER_ID_HEADER_NAME}

kakao:
  client-id: ${secrets.DEV_KAKAO_CLIENT_ID}
  redirect-uri: ${secrets.DEV_KAKAO_REDIRECT_URI}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace